Styling login and signup pages
Hack4Impact-UMD/childrens-cancer-foundation pull request #11
Opened 2024-10-16 21:45 UTC by eileendchen

Notes:
- did not implement the image yet as figma comment says image is still coming in
- will fix styling, add padding/margins when image is decided

2024-10-20 01:45 UTC, ardada2468 commented
Looks great!
Just some minor things: 

1.  We need to do email validation, so if someone enters an invalid email it will show red text saying 'please enter valid email'
2.  We need to show an error when the passwords do not match, under the 2nd password button


![image](https://github.com/user-attachments/assets/fe4844f0-97df-4393-b771-dee33feca0d0)

2024-10-20 01:50 UTC, ardada2468 requested changes
Looks great!
Just some minor things: 

1.  We need to show an error when the passwords do not match, under the 2nd password button


![image](https://github.com/user-attachments/assets/fe4844f0-97df-4393-b771-dee33feca0d0)

2024-10-22 23:38 UTC, jdlane commented on react-app/ccf/src/pages/login.tsx
In order to keep our code more readable, we should ideally keep logic like the "login" function in a separate file (something like accountmanager.tsx), that way we can also keep similar account code in the same file. Same goes for CSS, it would be better in a separate file.

2024-10-22 23:40 UTC, jdlane commented on react-app/ccf/src/pages/signup.tsx
See my comment on login.tsx. We should try to keep logic separate from HTML/jsx separate from css.

2024-10-25 00:53 UTC, jdlane reviewed
Nice work. The create account page was actually a task for other engineers so that might get deleted, but I appreciate the effort.

2024-10-25 18:17 UTC, merged