Starting layout for app form frontend
Hack4Impact-UMD/childrens-cancer-foundation pull request #18
Opened 2024-10-22 04:07 UTC by throwExceptionPlease

Starting layout for the app form frontend skeleton--just added files needed for implementation

2024-10-23 01:31 UTC, jdlane requested changes
This code throws errors trying to go to the second page because there are radio button <input> tags with child elements, which isn't allowed. Try looking into <label> tags instead for those fields. Also, make sure to give those radio buttons a "name" property so that they are connected.

Also, make sure to implement the little things for good user experience. Buttons should change color when hovered and the application steps at the top should probably get highlighted when the user is on that page.

2024-10-24 08:17 UTC, throwExceptionPlease commented
> This code throws errors trying to go to the second page because there are radio button tags with child elements, which isn't allowed. Try looking into tags instead for those fields. Also, make sure to give those radio buttons a "name" property so that they are connected.
> 
> Also, make sure to implement the little things for good user experience. Buttons should change color when hovered and the application steps at the top should probably get highlighted when the user is on that page.

yep sorry, shouldve mentioned that i just pushed this just to get something up here. but ill def implement the feedback thanks

2024-10-24 21:22 UTC, jdlane commented
> > This code throws errors trying to go to the second page because there are radio button tags with child elements, which isn't allowed. Try looking into tags instead for those fields. Also, make sure to give those radio buttons a "name" property so that they are connected.
> > Also, make sure to implement the little things for good user experience. Buttons should change color when hovered and the application steps at the top should probably get highlighted when the user is on that page.
> 
> yep sorry, shouldve mentioned that i just pushed this just to get something up here. but ill def implement the feedback thanks. i didnt even realize i had child elements in the radio btns LOOLOL

No worries! In the future you can just push those changes without opening the PR so that me and Arnav don't try to review it before it's done.

2024-11-20 03:53 UTC, jdlane requested changes
Hey Hanish, sorry for the delay in getting this reviewed. 
There are a couple issues:
- The breadcrumb indicator at the top has a line going through the circle when it's white
- Only the first two radio buttons work in the application questions, the others can't be selected
- The file selector isn't working
- The buttons should use the shared button component in the components folder

2024-11-20 03:53 UTC, jdlane commented on react-app/ccf/src/App.tsx
There are repeated imports in this file, preventing this from compiling

2024-11-20 03:53 UTC, jdlane commented on react-app/ccf/src/application-form/ApplicationForm.tsx
For buttons we should use the shared button component in components/button to avoid repeated code.

2024-11-21 01:52 UTC, mistahanish commented on react-app/ccf/src/application-form/ApplicationForm.tsx
Ah! Sorry about that will update the changes soon.

2024-12-05 02:01 UTC, mistahanish commented
Still need to fix file upload button, and still need to add shared button component for all buttons.

2025-02-18 01:04 UTC, merged